baseURL = "https://aitoolreviewr.com/"
languageCode = "en"
title = "AI Tool Review"

[frontmatter]
  date = ["date"]
  lastmod = ["lastmod"]

[permalinks]
  articles = "/articles/:filename/"

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
