// Search Index - AI ToolSpot
// Generated by Hugo

const searchIndex = [
  {{ range $i, $page := .Site.RegularPages }}
  {{ if $i }},{{ end }}  {
    title: {{ $page.Title | jsonify }},
    url: {{ $page.RelPermalink | jsonify }},
    category: {{ if $page.Params.categories }}{{ index $page.Params.categories 0 | jsonify }}{{ else }}"General"{{ end }},
    excerpt: {{ $page.Description | jsonify }}
  }{{ end }}
];
