baseURL = "https://aitoolreviewr.com/"
languageCode = "en"
title = "AI Tool Review"
publishDir = "../../public"

[frontmatter]
  date = ["date"]
  lastmod = ["lastmod"]

[permalinks]
  articles = "/articles/:filename/"
  page = "/:filename/"

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
